// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/exchange/exchange_manage_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/exchange/exchange_manage_service.go -destination=internal/service/exchange/mock/exchange_manage_service_mock.go
//

// Package mock_exchange is a generated GoMock package.
package mock_exchange

import (
	model "exchange-service/internal/model"
	persistence "exchange-service/internal/persistence"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExchangeManageService is a mock of ExchangeManageService interface.
type MockExchangeManageService struct {
	ctrl     *gomock.Controller
	recorder *MockExchangeManageServiceMockRecorder
}

// MockExchangeManageServiceMockRecorder is the mock recorder for MockExchangeManageService.
type MockExchangeManageServiceMockRecorder struct {
	mock *MockExchangeManageService
}

// NewMockExchangeManageService creates a new mock instance.
func NewMockExchangeManageService(ctrl *gomock.Controller) *MockExchangeManageService {
	mock := &MockExchangeManageService{ctrl: ctrl}
	mock.recorder = &MockExchangeManageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExchangeManageService) EXPECT() *MockExchangeManageServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockExchangeManageService) Create(exchange model.Exchange) (model.Exchange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", exchange)
	ret0, _ := ret[0].(model.Exchange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockExchangeManageServiceMockRecorder) Create(exchange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExchangeManageService)(nil).Create), exchange)
}

// Delete mocks base method.
func (m *MockExchangeManageService) Delete(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockExchangeManageServiceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExchangeManageService)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockExchangeManageService) GetAll() ([]model.Exchange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]model.Exchange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockExchangeManageServiceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockExchangeManageService)(nil).GetAll))
}

// GetAllWithPage mocks base method.
func (m *MockExchangeManageService) GetAllWithPage(page, size int) (persistence.Page[model.Exchange], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWithPage", page, size)
	ret0, _ := ret[0].(persistence.Page[model.Exchange])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWithPage indicates an expected call of GetAllWithPage.
func (mr *MockExchangeManageServiceMockRecorder) GetAllWithPage(page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWithPage", reflect.TypeOf((*MockExchangeManageService)(nil).GetAllWithPage), page, size)
}

// GetById mocks base method.
func (m *MockExchangeManageService) GetById(id int) (model.Exchange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(model.Exchange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockExchangeManageServiceMockRecorder) GetById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockExchangeManageService)(nil).GetById), id)
}

// Update mocks base method.
func (m *MockExchangeManageService) Update(id int, exchange model.Exchange) (model.Exchange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, exchange)
	ret0, _ := ret[0].(model.Exchange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockExchangeManageServiceMockRecorder) Update(id, exchange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExchangeManageService)(nil).Update), id, exchange)
}
