// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/exchange/exchange_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/exchange/exchange_service.go -destination=internal/service/exchange/mock/exchange_service_mock.go
//

// Package mock_exchange is a generated GoMock package.
package mock_exchange

import (
	model "exchange-service/internal/model"
	persistence "exchange-service/internal/persistence"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExchangeService is a mock of ExchangeService interface.
type MockExchangeService struct {
	ctrl     *gomock.Controller
	recorder *MockExchangeServiceMockRecorder
}

// MockExchangeServiceMockRecorder is the mock recorder for MockExchangeService.
type MockExchangeServiceMockRecorder struct {
	mock *MockExchangeService
}

// NewMockExchangeService creates a new mock instance.
func NewMockExchangeService(ctrl *gomock.Controller) *MockExchangeService {
	mock := &MockExchangeService{ctrl: ctrl}
	mock.recorder = &MockExchangeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExchangeService) EXPECT() *MockExchangeServiceMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockExchangeService) GetAll() ([]model.Exchange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]model.Exchange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockExchangeServiceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockExchangeService)(nil).GetAll))
}

// GetAllWithPage mocks base method.
func (m *MockExchangeService) GetAllWithPage(page, size int) (persistence.Page[model.Exchange], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWithPage", page, size)
	ret0, _ := ret[0].(persistence.Page[model.Exchange])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWithPage indicates an expected call of GetAllWithPage.
func (mr *MockExchangeServiceMockRecorder) GetAllWithPage(page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWithPage", reflect.TypeOf((*MockExchangeService)(nil).GetAllWithPage), page, size)
}

// GetById mocks base method.
func (m *MockExchangeService) GetById(id int64) (model.Exchange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(model.Exchange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockExchangeServiceMockRecorder) GetById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockExchangeService)(nil).GetById), id)
}

// Update mocks base method.
func (m *MockExchangeService) Update(id int64, exchange model.Exchange) (model.Exchange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, exchange)
	ret0, _ := ret[0].(model.Exchange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockExchangeServiceMockRecorder) Update(id, exchange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExchangeService)(nil).Update), id, exchange)
}
