// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/currency_handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/api/currency_handler.go -destination=internal/api/mock/currency_handler_mock.go
//

// Package mock_api is a generated GoMock package.
package mock_api

import (
	reflect "reflect"

	echo "github.com/labstack/echo/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockCurrencyHandler is a mock of CurrencyHandler interface.
type MockCurrencyHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCurrencyHandlerMockRecorder
}

// MockCurrencyHandlerMockRecorder is the mock recorder for MockCurrencyHandler.
type MockCurrencyHandlerMockRecorder struct {
	mock *MockCurrencyHandler
}

// NewMockCurrencyHandler creates a new mock instance.
func NewMockCurrencyHandler(ctrl *gomock.Controller) *MockCurrencyHandler {
	mock := &MockCurrencyHandler{ctrl: ctrl}
	mock.recorder = &MockCurrencyHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurrencyHandler) EXPECT() *MockCurrencyHandlerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCurrencyHandler) Create(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCurrencyHandlerMockRecorder) Create(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCurrencyHandler)(nil).Create), c)
}

// Delete mocks base method.
func (m *MockCurrencyHandler) Delete(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCurrencyHandlerMockRecorder) Delete(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCurrencyHandler)(nil).Delete), c)
}

// GetAll mocks base method.
func (m *MockCurrencyHandler) GetAll(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCurrencyHandlerMockRecorder) GetAll(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCurrencyHandler)(nil).GetAll), c)
}

// GetById mocks base method.
func (m *MockCurrencyHandler) GetById(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetById indicates an expected call of GetById.
func (mr *MockCurrencyHandlerMockRecorder) GetById(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockCurrencyHandler)(nil).GetById), c)
}

// HandleRoutes mocks base method.
func (m *MockCurrencyHandler) HandleRoutes(e *echo.Echo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleRoutes", e)
}

// HandleRoutes indicates an expected call of HandleRoutes.
func (mr *MockCurrencyHandlerMockRecorder) HandleRoutes(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRoutes", reflect.TypeOf((*MockCurrencyHandler)(nil).HandleRoutes), e)
}

// Update mocks base method.
func (m *MockCurrencyHandler) Update(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCurrencyHandlerMockRecorder) Update(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCurrencyHandler)(nil).Update), c)
}
