// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/exchange_handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/api/exchange_handler.go -destination=internal/api/mock/exchange_handler_mock.go
//

// Package mock_api is a generated GoMock package.
package mock_api

import (
	reflect "reflect"

	echo "github.com/labstack/echo/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockExchangeHandler is a mock of ExchangeHandler interface.
type MockExchangeHandler struct {
	ctrl     *gomock.Controller
	recorder *MockExchangeHandlerMockRecorder
}

// MockExchangeHandlerMockRecorder is the mock recorder for MockExchangeHandler.
type MockExchangeHandlerMockRecorder struct {
	mock *MockExchangeHandler
}

// NewMockExchangeHandler creates a new mock instance.
func NewMockExchangeHandler(ctrl *gomock.Controller) *MockExchangeHandler {
	mock := &MockExchangeHandler{ctrl: ctrl}
	mock.recorder = &MockExchangeHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExchangeHandler) EXPECT() *MockExchangeHandlerMockRecorder {
	return m.recorder
}

// Buy mocks base method.
func (m *MockExchangeHandler) Buy(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Buy", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Buy indicates an expected call of Buy.
func (mr *MockExchangeHandlerMockRecorder) Buy(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Buy", reflect.TypeOf((*MockExchangeHandler)(nil).Buy), c)
}

// Create mocks base method.
func (m *MockExchangeHandler) Create(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockExchangeHandlerMockRecorder) Create(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExchangeHandler)(nil).Create), c)
}

// Delete mocks base method.
func (m *MockExchangeHandler) Delete(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockExchangeHandlerMockRecorder) Delete(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExchangeHandler)(nil).Delete), c)
}

// GetAll mocks base method.
func (m *MockExchangeHandler) GetAll(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockExchangeHandlerMockRecorder) GetAll(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockExchangeHandler)(nil).GetAll), c)
}

// GetById mocks base method.
func (m *MockExchangeHandler) GetById(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetById indicates an expected call of GetById.
func (mr *MockExchangeHandlerMockRecorder) GetById(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockExchangeHandler)(nil).GetById), c)
}

// HandleRoutes mocks base method.
func (m *MockExchangeHandler) HandleRoutes(e *echo.Echo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleRoutes", e)
}

// HandleRoutes indicates an expected call of HandleRoutes.
func (mr *MockExchangeHandlerMockRecorder) HandleRoutes(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRoutes", reflect.TypeOf((*MockExchangeHandler)(nil).HandleRoutes), e)
}

// HistoricPrice mocks base method.
func (m *MockExchangeHandler) HistoricPrice(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HistoricPrice", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// HistoricPrice indicates an expected call of HistoricPrice.
func (mr *MockExchangeHandlerMockRecorder) HistoricPrice(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HistoricPrice", reflect.TypeOf((*MockExchangeHandler)(nil).HistoricPrice), c)
}

// PriceFor mocks base method.
func (m *MockExchangeHandler) PriceFor(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PriceFor", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// PriceFor indicates an expected call of PriceFor.
func (mr *MockExchangeHandlerMockRecorder) PriceFor(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PriceFor", reflect.TypeOf((*MockExchangeHandler)(nil).PriceFor), c)
}

// Sell mocks base method.
func (m *MockExchangeHandler) Sell(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sell", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sell indicates an expected call of Sell.
func (mr *MockExchangeHandlerMockRecorder) Sell(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sell", reflect.TypeOf((*MockExchangeHandler)(nil).Sell), c)
}

// Update mocks base method.
func (m *MockExchangeHandler) Update(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockExchangeHandlerMockRecorder) Update(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExchangeHandler)(nil).Update), c)
}
